---

# for complete list of usable vars, please check https://github.com/geerlingguy/ansible-role-nginx
nginx_service_state: started
nginx_service_enabled: yes
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k"
nginx_vhosts:
  - server_name: "prometheus.example.com"
    template: "templates/prometheus.example.com.vhost.j2"
    filename: "prometheus.example.com.conf"
gzip_enabled: false
