---

- name: Gather facts for all the hosts
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Gather facts
      setup:

- name: Install Nginx
  hosts: ubuntu
  become: true
  gather_facts: true
  roles:
    - geerlingguy.nginx
